### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by CHISOM96**
## Description
I added a hero section and a footer to the home page. The footer includes social icons that will enable users to connect with the project on different platforms. I also added a .htaccess file to enable HTML files load without the extension. 

This PR is a fix for issue #24 and #25 

## How Has This Been Tested?
This code was tested using lighthouse.

## Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have added necessary inline code documentation
- [ x] I have added tests that prove my fix is effective and that this feature works
coh lighthouse
rest of the page

### CODE REVIEW

**Review by Josconic — APPROVED** [review]
Well done. Keep it up. You are doing great. Good job

**Comment by oyinkan** [comment]
Well done

**Review by oyinkan — APPROVED** [review]
Approved

**Comment by Cyber-Lord** [comment]
@CHISOM96 can you improve the responsiveness @oyinkan for the registration form can  you add account type and make the page use the site header for easy navigation?

**Pull request merged**
