### PR TITLE
Homepage and Header

### PR DESCRIPTION
**Pull request by CHISOM96**
## Description
Fix for Issue #2 and #3 

## Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have added necessary inline code documentation

### CODE REVIEW

**Review by Josconic — DISMISSED** [review]

**Review by Cyber-Lord — DISMISSED** [review]
Looks good

**Review by oyinkan — DISMISSED** [review]
Well done. Good job.

**Review by oyinkan — APPROVED** [review]

**Comment by sam-karis** [comment]
@CHISOM96 Good job on working on this. Please address the following
- Add relevant screenshots e.g the home page
- Add the necessary steps to follow to be able to run and test your work locally
- squash you commit

**Comment by sam-karis** [comment]
Also just a follow what did the team agree about writing tests, in your workflow?

**Review by sam-karis — CHANGES_REQUESTED** [review]
Please address the issues I have mentioned above

**Review by Josconic — APPROVED** [review]
Welldone

**Comment by CHISOM96** [comment]
@sam-karis I used Lighthouse to audit the homepage. I have attached screenshots of what the page currently looks like and the lighthouse report 
Homepage screenshot
lighthouse

**Comment by CHISOM96** [comment]
@sam-karis To test it locally: 

1. Clone this repo to your local machine, switch to the frontend branch.
2.  Use command prompt or you preferred tool, cd into the repo on your local machine.
3.  Start a live server. (I use http-server)
4. Open the address in chrome.  i.e http://localhost:8080/src/frontend/index.html.
5. Open developer tools and click audit or Download the Lighthouse Chrome extension from the Chrome Web Store. When installed it places a Lighthouse Icon in your taskbar.

**Comment by CHISOM96** [comment]
@sam-karis I have squashed all the commits into 880b88e8854ef8f2c8bd81368ddf45b8fa9fd3d1

**Pull request merged**
