### PR TITLE
User dashboard

### PR DESCRIPTION
**Pull request by CHISOM96**
## Description
This Pr contains a values page and a pop-up quiz before the user can move to the next stage.

### CODE REVIEW

**Comment by Josconic** [comment]
Work on the issues raised by Codacy, it is important. Good job. Keep it up.

**Comment by Abubakarharuna10** [comment]
.

**Review by oyinkan — DISMISSED** [review]

**Comment by CHISOM96** [comment]
@Josconic I have fixed all the css issues. Feel free to merge

**Review by Josconic — APPROVED** [review]
good

**Pull request merged**
